---
dante_enable: true
dante_port: 1080
dante_direct: true

## config customization
dante_logoutput: syslog
dante_user_privileged: root

dante_timeout_negotiate: 300
dante_timeout_io: 3600

## dante username must start with 'dante_' because it's global linux user
dante_user: dante_socks
dante_pass: secret

dante_noauth_listen_addresses:
  - 127.0.0.0/24
dante_noauth_client_addresses:
  - 127.0.0.0/24

dante_external_addr:
  # - dante_external_addr: "{{ ansible_default_ipv4.interface }}"
  - "{{ ansible_default_ipv4.address |default('') }}"
  - "{{ ansible_default_ipv6.address |default('') }}"

## see: https://www.inet.no/dante/doc/1.4.x/config/logging.html
dante_verbose_log: false

## see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hash-filters
dante_salt: "{{ 32100 |random(seed=inventory_hostname) |string }}"
...
