---
- name: ensure dante log file exists
  ansible.builtin.copy:
    dest: /var/log/dante.log
    content: ""
    force: false
    owner: syslog
    group: adm
    mode: 0640
  notify: restart syslog service

- name: configure syslog for dante
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/34-dante.conf
    content: |
      :programname,isequal,"danted" /var/log/dante.log
      & stop
    force: true
    mode: 0644
  notify: restart syslog service

- name: rotate dante log file
  ansible.builtin.copy:
    dest: /etc/logrotate.d/dante
    content: |
      /var/log/dante.log {
          weekly
          maxsize 1M
          missingok
          rotate 4
          notifempty
          {{ commentout }}compress
          {{ commentout }}delaycompress
          sharedscripts
          postrotate
              invoke-rc.d rsyslog rotate > /dev/null 2> /dev/null
          endscript
      }
    force: true
    mode: 0644
  vars:
    commentout: "{{ compress |ternary('','#') }}"
    compress: "{{ lin_compress_logs |bool or lin_compress_logs is none }}"
...
