---
- name: create directory for nx authorized keys
  ansible.builtin.file:
    state: directory
    path: ~/.nx/config
    mode: 0755

- name: create authorized keys stub if none existed
  ansible.builtin.copy:
    dest: ~/.ssh/authorized_keys
    content: ""
    mode: 0600
    force: false

- name: link ssh authorized keys to nx config
  ansible.builtin.file:
    state: link
    src: ~/.ssh/authorized_keys
    dest: ~/.nx/config/authorized.crt

- name: add DISPLAY variable to the user's bashrc file
  ansible.builtin.lineinfile:
    ## the path file must correspond with role ivansible.devel.user
    ## https://github.com/ivansible/devel/blob/master/roles/user/tasks/bashrc.yml
    ## noqa 208
    path: ~/.local/bashrc/1env.sh
    line: "export DISPLAY=:{{ lin_nxserver_display }}"
    create: true
  when: lin_nxserver_display |default('')
...
